# Generated by Django 3.2.5 on 2022-01-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crime_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crimeid', models.CharField(max_length=11)),
                ('psid', models.CharField(max_length=11)),
                ('doffence', models.DateTimeField()),
                ('dreport', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='example2',
            name='question',
        ),
        migrations.DeleteModel(
            name='example1',
        ),
        migrations.DeleteModel(
            name='example2',
        ),
    ]
