# Generated by Django 3.2.5 on 2022-01-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220121_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='police_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=11)),
                ('location', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Delhi', 'Delhi'), ('Pune', 'Pune'), ('Cochin', 'Cochin')], default='Bangalore', max_length=20)),
                ('phoneno', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='crime_register',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='crime_register',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('CLOSED', 'CLOSED')], default='PROCESSING', max_length=20),
        ),
        migrations.CreateModel(
            name='witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witnessid', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=2000)),
                ('phoneno', models.IntegerField()),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('CLOSED', 'CLOSED')], default='PROCESSING', max_length=20)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crime_register')),
            ],
        ),
        migrations.CreateModel(
            name='victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=11)),
                ('phoneno', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crime_register')),
            ],
        ),
        migrations.CreateModel(
            name='officer_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=2000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non Binary', 'Non Binary'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=20)),
                ('position', models.CharField(max_length=11)),
                ('psid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.police_station')),
            ],
        ),
        migrations.CreateModel(
            name='accused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accusedid', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=2000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non Binary', 'Non Binary'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=20)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crime_register')),
            ],
        ),
        migrations.AlterField(
            model_name='crime_register',
            name='psid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.police_station'),
        ),
    ]
